version: '3'
services:
  app:
    build: .
    ports:
      - "3000:5000"
    environment:
      - EMAIL_USER=sauravshete9@gmail.com
      - EMAIL_PASS=JSXWUIEDI3IS
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro

