# Build stage for React frontend
FROM node:14 as frontend-build

WORKDIR /usr/src/app/frontend

COPY frontend/package*.json ./

RUN npm install

COPY frontend/ ./

RUN npm run build

FROM node:14

WORKDIR /usr/src/app

COPY backend/package*.json ./

RUN npm install

COPY backend/ ./

COPY --from=frontend-build /usr/src/app/frontend/build ./frontend/build

EXPOSE 5000

CMD ["node", "index.js"]










# FROM node:14.17.0-alpine3.13

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# EXPOSE 5000

# CMD ["npm", "start"]